// Package render turns a Digest (plus an optional LLM narrative) into the final
// Markdown journal, and produces the compact plain-text digest fed to the LLM
// prompt. It never imports synth, avoiding an import cycle.
package render

import (
	"fmt"
	"sort"
	"strings"

	"github.com/smm-h/reposummary/internal/digest"
	"github.com/smm-h/reposummary/internal/gitdata"
)

// otherLimit caps how many "Other" commits are listed before summarizing the rest.
const otherLimit = 40

// llmSubjectLimit caps how many subjects per bucket go into the LLM digest.
const llmSubjectLimit = 40

// sectionOrder is the fixed order of change sections in the journal.
var sectionOrder = []struct {
	key    string
	header string
}{
	{"breaking", "## Breaking changes"},
	{"feature", "## Features"},
	{"fix", "## Fixes"},
	{"other", "## Other"},
}

// Markdown renders the full journal for a digest and narrative.
func Markdown(d digest.Digest, narrative, version string) string {
	var b strings.Builder

	// Header.
	fmt.Fprintf(&b, "# Journal — %s\n\n", d.RepoName)
	b.WriteString("**" + d.WindowLabel + "**")
	if d.HasDates {
		fmt.Fprintf(&b, " · %s → %s", d.DateStart.Format("2006-01-02"), d.DateEnd.Format("2006-01-02"))
	}
	b.WriteString("\n")

	if d.TotalCommits == 0 {
		b.WriteString("\n_No activity in this window._\n")
		b.WriteString(footer(version))
		return b.String()
	}

	if narrative != "" {
		fmt.Fprintf(&b, "\n## Summary\n\n%s\n", narrative)
	}

	// At a glance.
	b.WriteString("\n## At a glance\n\n")
	fmt.Fprintf(&b, "- Commits: %d\n", d.TotalCommits)
	fmt.Fprintf(&b, "- Files changed: %d\n", d.TotalFiles)
	fmt.Fprintf(&b, "- +%d / -%d lines\n", d.Insertions, d.Deletions)
	fmt.Fprintf(&b, "- Authors: %d\n", len(d.Authors))
	fmt.Fprintf(&b, "- Merges: %d\n", d.Merges)
	fmt.Fprintf(&b, "- Tags: %s\n", tagList(d.Tags))

	// Change sections.
	for _, sec := range sectionOrder {
		commits := d.Buckets[sec.key]
		if len(commits) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\n%s\n\n", sec.header)
		if sec.key == "other" && len(commits) > otherLimit {
			for _, c := range commits[:otherLimit] {
				fmt.Fprintf(&b, "- %s (`%s`)\n", digest.CleanSubject(c), c.Short)
			}
			fmt.Fprintf(&b, "- …and %d more commits.\n", len(commits)-otherLimit)
		} else {
			for _, c := range commits {
				fmt.Fprintf(&b, "- %s (`%s`)\n", digest.CleanSubject(c), c.Short)
			}
		}
	}

	// Active areas.
	if len(d.DirChurn) > 0 {
		b.WriteString("\n## Active areas\n\n")
		b.WriteString("| Directory | Touches |\n")
		b.WriteString("| --- | --- |\n")
		for _, kv := range topDirs(d.DirChurn, 8) {
			fmt.Fprintf(&b, "| %s | %d |\n", kv.key, kv.count)
		}
	}

	// Timeline (only when the window spans at most 31 distinct days).
	if len(d.CommitsByDay) > 0 && len(d.CommitsByDay) <= 31 {
		b.WriteString("\n## Timeline\n\n")
		b.WriteString("| Date | Commits |\n")
		b.WriteString("| --- | --- |\n")
		days := make([]string, 0, len(d.CommitsByDay))
		for day := range d.CommitsByDay {
			days = append(days, day)
		}
		sort.Strings(days)
		for _, day := range days {
			fmt.Fprintf(&b, "| %s | %d |\n", day, d.CommitsByDay[day])
		}
	}

	b.WriteString(footer(version))
	return b.String()
}

// footer returns the generated-by footer. The DOUBLE newline before "---" is
// required: a single "\n---" makes CommonMark parse the preceding line as a
// setext H2 heading.
func footer(version string) string {
	return fmt.Sprintf("\n\n---\n_Generated by reposummary v%s._", version)
}

// tagList joins tag names with ", ", or "none" when there are none.
func tagList(tags []gitdata.Tag) string {
	if len(tags) == 0 {
		return "none"
	}
	names := make([]string, len(tags))
	for i, t := range tags {
		names[i] = t.Name
	}
	return strings.Join(names, ", ")
}

type dirCount struct {
	key   string
	count int
}

// topDirs returns the top-n directories by churn, descending, with directory
// name as a stable tie-break.
func topDirs(churn map[string]int, n int) []dirCount {
	items := make([]dirCount, 0, len(churn))
	for k, v := range churn {
		items = append(items, dirCount{k, v})
	}
	sort.Slice(items, func(i, j int) bool {
		if items[i].count != items[j].count {
			return items[i].count > items[j].count
		}
		return items[i].key < items[j].key
	})
	if len(items) > n {
		items = items[:n]
	}
	return items
}

// DigestForLLM produces a compact plain-text digest for the LLM prompt.
func DigestForLLM(d digest.Digest) string {
	var b strings.Builder

	b.WriteString("WINDOW: " + d.WindowLabel + "\n")
	if d.HasDates {
		fmt.Fprintf(&b, "DATES: %s to %s\n", d.DateStart.Format("2006-01-02"), d.DateEnd.Format("2006-01-02"))
	}

	b.WriteString("\nAT A GLANCE:\n")
	fmt.Fprintf(&b, "- %d commits, %d files changed, +%d/-%d lines\n", d.TotalCommits, d.TotalFiles, d.Insertions, d.Deletions)
	fmt.Fprintf(&b, "- %d authors, %d merges\n", len(d.Authors), d.Merges)
	if len(d.Tags) > 0 {
		fmt.Fprintf(&b, "- tags: %s\n", tagList(d.Tags))
	}

	for _, sec := range sectionOrder {
		commits := d.Buckets[sec.key]
		if len(commits) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\n%s:\n", strings.ToUpper(sec.key))
		limit := len(commits)
		truncated := 0
		if limit > llmSubjectLimit {
			truncated = limit - llmSubjectLimit
			limit = llmSubjectLimit
		}
		for _, c := range commits[:limit] {
			fmt.Fprintf(&b, "- %s\n", digest.CleanSubject(c))
		}
		if truncated > 0 {
			fmt.Fprintf(&b, "- (+%d more)\n", truncated)
		}
	}

	if len(d.DirChurn) > 0 {
		b.WriteString("\nTOP DIRECTORIES:\n")
		for _, kv := range topDirs(d.DirChurn, 8) {
			fmt.Fprintf(&b, "- %s (%d)\n", kv.key, kv.count)
		}
	}

	return b.String()
}
