package render

import (
	"strings"
	"testing"
	"time"

	"github.com/smm-h/reposummary/internal/digest"
	"github.com/smm-h/reposummary/internal/gitdata"
)

func sampleDigest() digest.Digest {
	day1, _ := time.Parse(time.RFC3339, "2026-01-01T10:00:00Z")
	day2, _ := time.Parse(time.RFC3339, "2026-01-02T10:00:00Z")
	return digest.Digest{
		RepoName:     "myrepo",
		WindowLabel:  "Full history",
		DateStart:    day1,
		DateEnd:      day2,
		HasDates:     true,
		TotalCommits: 4,
		TotalFiles:   4,
		Insertions:   20,
		Deletions:    3,
		Merges:       0,
		Authors:      map[string]int{"Tester": 4},
		Buckets: map[string][]gitdata.Commit{
			"feature":  {{Short: "a1", Subject: "feat: add scanner"}},
			"fix":      {{Short: "b2", Subject: "fix: correct off-by-one"}},
			"breaking": {{Short: "d4", Subject: "feat!: change API shape"}},
			"other":    {{Short: "e5", Subject: "refactor internals"}},
		},
		Tags:         []gitdata.Tag{{Name: "v0.1.0"}},
		DirChurn:     map[string]int{"src": 3, "": 1},
		CommitsByDay: map[string]int{"2026-01-01": 2, "2026-01-02": 2},
	}
}

func TestMarkdownSections(t *testing.T) {
	md := Markdown(sampleDigest(), "", "0.1.0")

	for _, want := range []string{
		"# Journal — myrepo",
		"## At a glance",
		"## Breaking changes",
		"## Features",
		"## Fixes",
		"## Other",
		"## Active areas",
		"## Timeline",
	} {
		if !strings.Contains(md, want) {
			t.Errorf("markdown missing %q:\n%s", want, md)
		}
	}
}

func TestMarkdownFooterSetextRegression(t *testing.T) {
	md := Markdown(sampleDigest(), "", "0.1.0")
	if !strings.Contains(md, "\n\n---\n") {
		t.Errorf("footer must contain the double-newline before ---:\n%q", md)
	}
	if !strings.HasSuffix(md, "_Generated by reposummary v0.1.0._") {
		t.Errorf("footer missing generated-by line:\n%s", md)
	}
}

func TestMarkdownNarrative(t *testing.T) {
	md := Markdown(sampleDigest(), "Lots happened this week.", "0.1.0")
	if !strings.Contains(md, "## Summary") {
		t.Errorf("narrative should add a Summary section:\n%s", md)
	}
	if !strings.Contains(md, "Lots happened this week.") {
		t.Errorf("narrative text missing:\n%s", md)
	}
	idx := strings.Index(md, "Lots happened this week.")
	summaryIdx := strings.Index(md, "## Summary")
	if summaryIdx == -1 || idx < summaryIdx {
		t.Errorf("narrative should appear under ## Summary")
	}
}

func TestMarkdownEmpty(t *testing.T) {
	d := digest.Digest{RepoName: "empty", WindowLabel: "Today (2026-07-08)"}
	md := Markdown(d, "", "0.1.0")
	if !strings.Contains(md, "_No activity") {
		t.Errorf("empty digest should say no activity:\n%s", md)
	}
	if strings.Contains(md, "## At a glance") {
		t.Errorf("empty digest should not render sections:\n%s", md)
	}
	if !strings.Contains(md, "\n\n---\n") {
		t.Errorf("empty digest must still have proper footer:\n%q", md)
	}
}

func TestDigestForLLM(t *testing.T) {
	out := DigestForLLM(sampleDigest())
	for _, want := range []string{"WINDOW: Full history", "add scanner", "src"} {
		if !strings.Contains(out, want) {
			t.Errorf("LLM digest missing %q:\n%s", want, out)
		}
	}
}
